# Generated by Django 5.0.14 on 2026-08-18 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiq_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1860), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='uq_album_track_number'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='uq_album_song'),
        ),
    ]
