# Generated by Django 5.0.14 on 2026-08-18 14:16

import django.core.validators
import musiq_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musiq_catalog", "0002_alter_albumsong_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_year",
            field=models.IntegerField(validators=[musiq_catalog.models.validate_release_year]),
        ),
        migrations.AlterField(
            model_name="albumsong",
            name="track_number",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
